#!/bin/bash
rofi \
    -show window  \
    -window-format {c}\
    -show-icons \
    -kb-cancel "Alt+Escape,Escape" \
    -kb-accept-entry "!Alt-Tab,!Alt-Alt_L,!Alt_L,Return"\
    -kb-row-down "Alt+Tab,Alt+Down" \
    -kb-row-up "Alt+ISO_Left_Tab,Alt+Up" &
xdotool keyup Tab
xdotool key Tab
